"""Subclass of DatabaseFrame, which is generated by wxFormBuilder."""

import wx
import WattrGUI

# Implementing DatabaseFrame
class WattrDatabaseFrame( WattrGUI.DatabaseFrame ):
	def __init__( self, parent ):
		WattrGUI.DatabaseFrame.__init__( self, parent )
	
