"""Subclass of DatabaseSelectorDialog, which is generated by wxFormBuilder."""

import wx
import WattrGUI

# Implementing DatabaseSelectorDialog
class WattrDatabaseSelectorDialog( WattrGUI.DatabaseSelectorDialog ):
	def __init__( self, parent ):
		WattrGUI.DatabaseSelectorDialog.__init__( self, parent )
	
