"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import WattrGUI

# Implementing MainFrame
class WattrMainFrame( WattrGUI.MainFrame ):
	def __init__( self, parent ):
		WattrGUI.MainFrame.__init__( self, parent )
	
