"""Subclass of DatabaseSelectorFrame, which is generated by wxFormBuilder."""

import wx
import WattrGUI

# Implementing DatabaseSelectorFrame
class WattrDatabaseSelectorFrame( WattrGUI.DatabaseSelectorFrame ):
	def __init__( self, parent ):
		WattrGUI.DatabaseSelectorFrame.__init__( self, parent )
	
