"""Subclass of DeviceSelectorFrame, which is generated by wxFormBuilder."""

import wx
import WattrGUI

# Implementing DeviceSelectorFrame
class WattrDeviceSelectorFrame( WattrGUI.DeviceSelectorFrame ):
	def __init__( self, parent ):
		WattrGUI.DeviceSelectorFrame.__init__( self, parent )
	
