"""Subclass of GraphPanel, which is generated by wxFormBuilder."""
import matplotlib
matplotlib.use('WXAgg')
import matplotlib.cm as cm
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg
from matplotlib.figure import Figure
import wx
import wx.xrc as xrc
matplotlib.rc('image', origin='lower')
import numpy as np

import WattrGUI


# Implementing GraphPanel
class WattrGraphPanel( WattrGUI.GraphPanel ):

    def __init__(self, parent, fgsize=None, dpi=None):
        super(WattrGraphPanel, self).__init__(parent)
        self.figure = Figure(fgsize, dpi)
        self.canvas = FigureCanvasWxAgg(self, -1, self.figure)
        # Now put all into a sizer
        sizer = wx.BoxSizer(wx.VERTICAL)
        # This way of adding to sizer allows resizing
        sizer.Add(self.canvas, 1, wx.LEFT|wx.TOP|wx.GROW)
        # Best to allow the toolbar to resize!
        self.SetSizer(sizer)
        self.Fit()

    def init_plot_data(self):
        self.plot = self.figure.add_subplot(111)
        self.set_title("Test")
        self.plot.plot([1,2,3,4,5],[1,1,2,2,7], linewidth=2.0, label="test1")

    def set_title(self, title):
        self.plot.set_title(title)

    def show_graph(self, boolean):
        self.plot.grid(boolean)

    def set_label_x(self, label):
       self.plot.set_xlabel(label)

    def set_label_y(self, label):
       self.plot.set_ylabel(label)
