"""Subclass of DeviceSelectorDialog, which is generated by wxFormBuilder."""

import wx
import WattrGUI

# Implementing DeviceSelectorDialog
class WattrDeviceSelectorDialog( WattrGUI.DeviceSelectorDialog ):
	def __init__( self, parent ):
		WattrGUI.DeviceSelectorDialog.__init__( self, parent )
	
